### ISSUE TITLE
Foundries lose ownership

### ISSUE THREAD

**Issue by modukon** [darkforest-eth/client#10]
Sometimes foundries i already claimed appear to have no owner, as soon as i send energy to them they update and show that i am already the owner (long before the energy arrives)
Other people in discord have also experienced this bug.
I am not not sure if this applies only for foundries or also other planets, i have only experienced it with foundries.

**Comment by phated** [comment]
Thanks @modukon! This has been migrated to the internal tracker. There were like 10+ independent reports.
