### ISSUE TITLE
Issue with map import 

### ISSUE THREAD

**Issue by snowtigersoft** [darkforest-eth/client#13]
I found a issue with map import function. When I import a map with a planet removed, the planet missing forever, the miner cannot found it again.
Step 1: export the map with a selected range.
<img width="1423" alt="截屏2021-07-20 下午10 55 07" src="https://user-images.githubusercontent.com/3327253/126350820-3bc54da3-45ae-4d2c-9120-1a8eadd916dd.png">
Step 2: remove the biggest planet from the map file.
<img width="1835" alt="截屏2021-07-20 下午11 00 43" src="https://user-images.githubusercontent.com/3327253/126350950-347f0794-be27-4bf0-a553-fc613423762f.png">
Step 3: Import the modified map file to a new account. the planet missing!!!
<img width="1133" alt="截屏2021-07-20 下午11 02 48" src="https://user-images.githubusercontent.com/3327253/126351109-820c58c7-f13a-460b-acca-59e5677dccdb.png">
Step 4: Start mining, BUT CANOT FOUND THE PLANET AGAIN!!

https://user-images.githubusercontent.com/3327253/126352610-faf79ecd-0733-4719-bbcd-fe2f351cd9bd.mp4

**Comment by phated** [comment]
Maps are mined in chunks, if the chunk already exists, the location will not be hashed again. This is by design. Don't alter map data and don't accept map data from untrusted sources (like other people)!
