### ISSUE TITLE
[ERROR] An error occurred: RangeError: bad Memory initial size

### ISSUE THREAD

**Issue by wschwab** [darkforest-eth/client#5]
Hi!

I got a key for the v5 game, and am encountering an error when I try to play. I am able to load an account Dark Forest recognizes, and the key I received is recognized. I get to the part where the client is looking for a home planet for me, and then the output looks like this:
```
Hashed 2048 potential home planets...
Hashed 4096 potential home planets...
Hashed 6144 potential home planets...
INIT: calculating witness and proof
[TX ERROR]: bad Memory initial size
[ERROR] An error occurred: RangeError: bad Memory initial size
```
I've tried twice so far. Any thoughts?

Just in case it's relevant: I'm on Firefox 78.6.0esr (64-bit)

**Comment by jacobrosenthal** [comment]
Please direct support to the discord channel https://discord.com/invite/2u2TN6v8r6

**Comment by phated** [comment]
This is caused by your computer running out of memory. More recent versions of SnarkJS have slight memory-management improvements and this should happen less, but make sure to have 2gb or more of free RAM when trying to play DF
