### ISSUE TITLE
BUG with twitter rebind. 

### ISSUE THREAD

**Issue by suzumiya2014** [darkforest-eth/client#8]
I double-checked, and the most important problem now is that after I rebind Twitter to my new address, my new address cannot be found here https://api.zkga.me/leaderboard

0x149f119543239d0b102bc60e80d0965232229234
![image](https://user-images.githubusercontent.com/24888155/124227172-d00d8600-db3c-11eb-8028-17f2ee7fdf31.png)

And in fact, my Twitter is still pointing to the old address:0xb00d51d3992BC412f783D0e21EDcf952Ce651D91

I gave a planet to my Twitter address, and it proved that I and I are different now. I can’t find my new account in leaderboard and everything else is normal. Before I rebind my new address 0x149f to my old Twitter, I can still access https://api.zkga.me/leaderboard find my address 0x149f
![image](https://user-images.githubusercontent.com/24888155/124227019-90df3500-db3c-11eb-9a26-9019f1468e85.png)

Hope to see my address 0x149f119543239d0b102bc60e80d0965232229234 on the leaderboard.

![image](https://user-images.githubusercontent.com/24888155/124214251-8153f200-db24-11eb-9355-cccf824aa49e.png)
![image](https://user-images.githubusercontent.com/24888155/124214263-85800f80-db24-11eb-9fe6-62e66ab81e6e.png)

**Comment by suzumiya2014** [comment]
I really need a feature to unbind tweets, or some other way to make my address be found by http://api.zkga.me/leaderboard. My current score is in the top 63th, but the address will not be displayed on the leaderboard, and my Twitter actually points to the wrong old binding address.:cry:  So so so sad.
![image](https://user-images.githubusercontent.com/24888155/124237165-d0604e00-db49-11eb-8fc9-2183e95e2702.png)
![image](https://user-images.githubusercontent.com/24888155/124237252-e79f3b80-db49-11eb-84a2-9e6af232ebf4.png)

**Comment by suzumiya2014** [comment]
1. 0xb00d51d3992BC412f783D0e21EDcf952Ce651D91 verify @LittleWhite2018
   2. I give up
   3. I create a new account 0x149f119543239d0b102bc60e80d0965232229234
   4. I can see both 0x149f119543239d0b102bc60e80d0965232229234 with scores & 
      @LittleWhite2018 with N/A on leaderboard.
----- until now ,everything is right -----
   5. I want to verify my twitter with the new account i played. So i try to 0x149f119543239d0b102bc60e80d0965232229234  verify @LittleWhite2018
   6. It seems work fine in game. But now , I cannot find 0x149f119543239d0b102bc60e80d0965232229234 on leaderboard and @LittleWhite2018 still with N/A 
   7. I try to send a plante to @LittleWhite2018, it works, so @LittleWhite2018 still point to 0xb00d51d3992BC412f783D0e21EDcf952Ce651D91
   8. The result is I can not find 0x149f119543239d0b102bc60e80d0965232229234 on leaderboard anymore, I need help.

**Comment by suzumiya2014** [comment]
Thank you, I re-logged in and found that my account has been unlinked to Twitter. But I still cannot find my account on the leaderboard. Is there any other problem?
![image](https://user-images.githubusercontent.com/24888155/124352994-51950f00-dc36-11eb-88cf-1738844b1c5a.png)


In fact, before I re-bind, I could see my address 0x149f on the leaderboard, but I couldn’t see it after binding. Now it seems to be unbound, but I still can’t see it on the leaderboard.
My address 0x149f no longer shows the binding, but there seems to be a problem on the leaderboard side. In fact, the problem there is more serious for me.:rofl:
Should I try to bind another tweet? I am worried that this will cause new problems

**Comment by suzumiya2014** [comment]
![image](https://user-images.githubusercontent.com/24888155/124607847-cd928f80-dea0-11eb-9219-5d7fa905e6d5.png)

I really feel sad.

**Comment by suzumiya2014** [comment]
I can give the planet to others, but they can’t give it to me. If I send it to me, the address will not be saved. If it is sent to my bound Twitter, it will be sent to my original address, but I'm not using which address to play the game at all.I can give the planet to others, but they can’t give it to me. If I send it to me, the address will not be saved. If it is sent to my bound Twitter, it will be sent to my original address, but I'm not using which address to play the game at all.
![image](https://user-images.githubusercontent.com/24888155/124607964-e8650400-dea0-11eb-9fb3-8a11dc3a9ae7.png)

**Comment by suzumiya2014** [comment]
![image](https://user-images.githubusercontent.com/24888155/124608243-23ffce00-dea1-11eb-9858-9a5cf1d12ad6.png)

**Comment by phated** [comment]
This was reported fixed in https://twitter.com/darkforest_eth/status/1412907545069461509
